services:
  - type: web
    name: alerted-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://alertedthesis-backend.onrender.com/api
      - key: NEXT_PUBLIC_R2_URL
        value: https://022e50c9cb2cd84a296eddb3a68d0e28.r2.cloudflarestorage.com/alerted-storage